name: PR Lint and Test
on: [pull_request]

jobs:
  lintAndTest:
    name: Run Linter & Launch unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
